language: node_js
node_js:
  - 7
  - 6
  - 5
  - 4
before_install:
  - npm config set depth 0
  - npm install --global npm@4
after_success:
  - npm run build
  - semantic-release pre && npm publish && semantic-release post
notifications:
  email: false
sudo: false
